# Generated by Django 5.2.3 on 2025-06-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='search_count',
        ),
        migrations.AddField(
            model_name='keyword',
            name='custom_refresh_interval',
            field=models.PositiveIntegerField(blank=True, help_text='Custom refresh interval in seconds. Leave blank to use the global default.', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='last_searched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
